analyzer:
  exclude:
    [
      dart_package/**,
      feature_route_bloc/**,
      feature_page_bloc/**,
      flutter_package/**,
      ui_package/**,
      model_json/**,
      rest_frog/**,
      go_router_setup/**,
    ]
